[package]
name = "eth-types"
version = "0.1.0"
edition = "2021"
authors = ["The appliedzkp team"]
license = "MIT OR Apache-2.0"

[dependencies]
ethers-core = "0.6"
ethers-signers = "0.6"
hex = "0.4"
lazy_static = "1.4"
halo2_proofs = { version = "0.1.0-beta.1" }
regex = "1.5.4"
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
uint = "0.9.1"
itertools = "0.10"
secp256k1 = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", tag = "v2022_06_03", features = ["kzg"] }
libsecp256k1 = "0.7"
subtle = "2.4"
sha3 = "0.10"
ff = "0.11"
num = "0.4"
group = "0.11"
num-bigint = { version = "0.4" }

