name: Lints

# We only run these lints on trial-merges of PRs to reduce noise.
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  clippy:
    if: github.event.pull_request.draft == false

    name: Clippy
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          override: false
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          name: Clippy
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings
